### ISSUE TITLE
Add Ayurvedic books Sections

### ISSUE THREAD

**Issue by MUDITJAINN** [MUDITJAINN/Ayurveda-GPT#10]
Create a dedicated section on the website to showcase a collection of Ayurvedic books. This section should include book titles, authors, and brief descriptions, along with links to purchase or read the books online. The goal is to provide users with valuable resources for further learning about Ayurveda.

Expected Features:

A visually appealing grid or list of Ayurvedic books.
Include relevant details like title, author, description, and a link to the book.
Ensure the section is responsive and fits seamlessly with the current website design.

**Comment by albinsabu2023** [comment]
hey bro can you assign this to me .I can work on it
