### ISSUE TITLE
Create Resouces Section

### ISSUE THREAD

**Issue by MUDITJAINN** [MUDITJAINN/Ayurveda-GPT#23]
We need to create a "Resources" section on the Ayurveda GPT website. This section will provide users and contributors with access to valuable materials related to Ayurveda, AI, and natural health. It will be a centralized place for educational materials, tutorials, references, and any other relevant resources.

Requirements:

Add a Resources section to the website's navigation bar.
The section should include:
Ayurveda Knowledge: Articles, books, or references about Ayurvedic practices, principles, and herbs.
AI & GPT Tutorials: Resources explaining how AI and GPT-3 are used in the context of Ayurveda and health tech.
Health & Wellness Links: Links to trusted Ayurveda websites, wellness blogs, and natural health resources.

Organize the resources in user-friendly categories like:
Ayurveda Basics
AI in Healthcare
Herbal Remedies
Mental & Physical Wellness
The section should be easy to update with new resources as they become available.

Additional Considerations:
Ensure a visually appealing layout with clear headings and categories.
Provide a form or link for users to suggest resources for inclusion in this section.

**Comment by AdamLiga** [comment]
Hey, I would love to work on this. :)

**Comment by anushree0809** [comment]
Hi, I would like to take up this issue! 
Is there any specific design, or I can decide on my own as long as its neat and visually appealing?

**Comment by prashantrai-30** [comment]
Hey @MUDITJAINN can you assign this issue to me.

**Comment by M-DEV-1** [comment]
@MUDITJAINN If this issue is still open, can you assign this to me
